// This file is auto-generated by @hey-api/openapi-ts

import * as v from 'valibot';

import { buildClientParams, type Client, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { CreatePasteErrors, CreatePasteRequest, CreatePasteResponses, DeletePasteErrors, DeletePasteResponses, GetLimitsErrors, GetLimitsResponses, GetPasteErrors, GetPasteResponses, GetPastesErrors, GetPastesResponses, GetProfileErrors, GetProfileResponses, UpdatePasteErrors, UpdatePasteRequest, UpdatePasteResponses } from './types.gen';
import { vCreatePasteData, vCreatePasteResponse2, vDeletePasteData, vGetLimitsData, vGetLimitsResponse, vGetPasteData, vGetPasteResponse, vGetPastesData, vGetPastesResponse, vGetProfileData, vGetProfileResponse2, vUpdatePasteData, vUpdatePasteResponse } from './valibot.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get Public API limits
 *
 * Returns the limits of Public API usage for the current user
 */
export const getLimits = <ThrowOnError extends boolean = false>(options?: Options<never, ThrowOnError>) => (options?.client ?? client).get<GetLimitsResponses, GetLimitsErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(vGetLimitsData, data),
    responseValidator: async (data) => await v.parseAsync(vGetLimitsResponse, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/pub/user/limits',
    ...options
});

/**
 * Get pastes list
 *
 * Returns a list of pastes that belong to the current user
 */
export const getPastes = <ThrowOnError extends boolean = false>(parameters?: {
    offset?: number;
    limit?: number;
}, options?: Options<never, ThrowOnError>) => {
    const params = buildClientParams([parameters], [{ args: [{ in: 'query', key: 'offset' }, { in: 'query', key: 'limit' }] }]);
    return (options?.client ?? client).get<GetPastesResponses, GetPastesErrors, ThrowOnError>({
        requestValidator: async (data) => await v.parseAsync(vGetPastesData, data),
        responseValidator: async (data) => await v.parseAsync(vGetPastesResponse, data),
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/pub/user/records',
        ...options,
        ...params
    });
};

/**
 * Get profile
 *
 * Returns the profile of the current user
 */
export const getProfile = <ThrowOnError extends boolean = false>(options?: Options<never, ThrowOnError>) => (options?.client ?? client).get<GetProfileResponses, GetProfileErrors, ThrowOnError>({
    requestValidator: async (data) => await v.parseAsync(vGetProfileData, data),
    responseValidator: async (data) => await v.parseAsync(vGetProfileResponse2, data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/pub/user/profile',
    ...options
});

/**
 * Publish new paste
 *
 * Creates a new paste for the current user
 *
 * ### URL Shortening
 *
 * Provide a valid URL in the `content` field to create a shortened URL paste:
 * - It will redirect the user to the target URL when accessed from the browser
 * - The `contentType` will be set to `url`
 *
 * > [!note]
 * A valid URL is defined by the [WHATWG URL Specification](https://url.spec.whatwg.org/)<br />
 * Only **HTTP** and **HTTPS** protocols are allowed
 */
export const createPaste = <ThrowOnError extends boolean = false>(parameters: {
    createPasteRequest: CreatePasteRequest;
}, options?: Options<never, ThrowOnError>) => {
    const params = buildClientParams([parameters], [{ args: [{ key: 'createPasteRequest', map: 'body' }] }]);
    return (options?.client ?? client).post<CreatePasteResponses, CreatePasteErrors, ThrowOnError>({
        requestValidator: async (data) => await v.parseAsync(vCreatePasteData, data),
        responseValidator: async (data) => await v.parseAsync(vCreatePasteResponse2, data),
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/pub/records',
        ...options,
        ...params,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers,
            ...params.headers
        }
    });
};

/**
 * Delete paste
 *
 * Deletes a paste that belongs to the current user
 */
export const deletePaste = <ThrowOnError extends boolean = false>(parameters: {
    url: string;
}, options?: Options<never, ThrowOnError>) => {
    const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'url' }] }]);
    return (options?.client ?? client).delete<DeletePasteResponses, DeletePasteErrors, ThrowOnError>({
        requestValidator: async (data) => await v.parseAsync(vDeletePasteData, data),
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/pub/records/{url}',
        ...options,
        ...params
    });
};

/**
 * Get paste
 *
 * Returns a paste with the specified URL
 */
export const getPaste = <ThrowOnError extends boolean = false>(parameters: {
    url: string;
}, options?: Options<never, ThrowOnError>) => {
    const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'url' }] }]);
    return (options?.client ?? client).get<GetPasteResponses, GetPasteErrors, ThrowOnError>({
        requestValidator: async (data) => await v.parseAsync(vGetPasteData, data),
        responseValidator: async (data) => await v.parseAsync(vGetPasteResponse, data),
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/pub/records/{url}',
        ...options,
        ...params
    });
};

/**
 * Update paste
 *
 * Updates a paste that belongs to the current user. Only pastes with `contentType=text` can be updated.
 *
 * At least one field must be not null for a successful response
 */
export const updatePaste = <ThrowOnError extends boolean = false>(parameters: {
    url: string;
    updatePasteRequest: UpdatePasteRequest;
}, options?: Options<never, ThrowOnError>) => {
    const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'url' }, { key: 'updatePasteRequest', map: 'body' }] }]);
    return (options?.client ?? client).patch<UpdatePasteResponses, UpdatePasteErrors, ThrowOnError>({
        requestValidator: async (data) => await v.parseAsync(vUpdatePasteData, data),
        responseValidator: async (data) => await v.parseAsync(vUpdatePasteResponse, data),
        security: [{ scheme: 'bearer', type: 'http' }],
        url: '/pub/records/{url}',
        ...options,
        ...params,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers,
            ...params.headers
        }
    });
};
