// This file is auto-generated by @hey-api/openapi-ts

import type { GetLimitsResponse, GetPasteResponse, GetPastesResponse } from './types.gen';

const pastesLimitSchemaResponseTransformer = (data: any) => {
    if (data.resetsAt) {
        data.resetsAt = new Date(data.resetsAt);
    }
    return data;
};

const limitsResponseSchemaResponseTransformer = (data: any) => {
    data.pastesLimit = pastesLimitSchemaResponseTransformer(data.pastesLimit);
    return data;
};

export const getLimitsResponseTransformer = async (data: any): Promise<GetLimitsResponse> => {
    data = limitsResponseSchemaResponseTransformer(data);
    return data;
};

const getPasteModelSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    return data;
};

const pastesListResponseSchemaResponseTransformer = (data: any) => {
    data.pastes = data.pastes.map((item: any) => getPasteModelSchemaResponseTransformer(item));
    return data;
};

export const getPastesResponseTransformer = async (data: any): Promise<GetPastesResponse> => {
    data = pastesListResponseSchemaResponseTransformer(data);
    return data;
};

export const getPasteResponseTransformer = async (data: any): Promise<GetPasteResponse> => {
    data = getPasteModelSchemaResponseTransformer(data);
    return data;
};
