// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api.yaso.su' | 'https://api.log.rw' | (string & {});
};

export type ContentType = 'text' | 'url';

export type CreatePasteRequest = {
    /**
     * The URL of the paste, which can be used to access it.
     * Will be generated if not specified. Must not be used by existing paste
     */
    url?: null | string;
    /**
     * Expiration time in seconds. If not specified, paste will not expire
     */
    expirationTime?: null | number;
    /**
     * Optional code language for syntax highlighting
     */
    codeLanguage?: null | string;
    /**
     * Content of the paste. Can be plain text or a valid URL for URL shortening.
     *
     * When providing a URL, it will be automatically detected and treated as a shortened URL paste.
     *
     * > [!note]
     * The length of the paste is counted by the number of [UTF-16 code units](https://en.wikipedia.org/wiki/UTF-16#Description)
     */
    content: string;
};

export type CreatePasteResponse = {
    url: string;
    contentType: ContentType;
    textContentType?: null | TextContentType;
};

/**
 * Detailed error information for a specific field or validation issue
 */
export type DetailedErrorItem = {
    /**
     * The name of the field that caused the error
     */
    field?: string;
    /**
     * Human-readable error message describing the issue
     */
    message: string;
};

export type GetPasteModel = {
    /**
     * The URL of the paste, which can be used to access it
     */
    url: string;
    content: string;
    contentType: ContentType;
    createdAt: Date;
    textContentType?: null | TextContentType;
    /**
     * Optional code language for syntax highlighting
     */
    codeLanguage?: null | string;
    /**
     * Permissions of the current user for this paste
     */
    permissions: Array<PasteUserPermission>;
};

/**
 * The profile of the current user
 */
export type GetProfileResponse = {
    /**
     * Display name of the user, based on the linked auth services
     */
    displayName?: null | string;
    /**
     * The type of session that was used to make the current request
     */
    sessionType: SessionType;
    role: UserRole;
};

export type LimitsResponse = {
    /**
     * The number of pastes the user can create via the public API
     */
    pastesLimit: PastesLimit;
};

export type PastesLimit = {
    /**
     * The total number of pastes the user can create via the public API in the current window
     */
    limit?: number;
    /**
     * The number of pastes the user has already created via the public API in the current window
     */
    used?: number;
    /**
     * The time when the current window resets and the int PastesLimit.Used count goes back to 0
     */
    resetsAt?: Date;
};

export type PastesListResponse = {
    pastes: Array<GetPasteModel>;
    /**
     * Indicates whether there are more pastes to load after the ones included in this response
     */
    hasMore: boolean;
};

export type PasteUserPermission = 'edit' | 'delete';

/**
 * Problem details response
 */
export type ProblemDetailsResponse = {
    /**
     * The HTTP status code for this occurrence of the problem
     */
    status: number;
    /**
     * A short, human-readable summary of the problem type. Should only be displayed to users when the `errors` field is not present
     */
    title: string;
    /**
     * Optional array of detailed error items with field-specific information. Should be preferred for displaying to users
     */
    errors?: Array<DetailedErrorItem>;
};

/**
 * Rate limit exceeded error response following Problem Details format
 * > [!tip]
 * > All endpoints may return this response
 *
 */
export type RateLimitError = {
    status: '429';
    title: 'You have exceeded the rate limit. Please try again later.';
    /**
     * Number of seconds to wait before making a new request
     */
    retryAfter: number;
};

export type SessionType = 'web' | 'publicApi';

export type TextContentType = 'plainText' | 'code' | 'markdown';

export type UpdatePasteRequest = {
    /**
     * The URL of the paste, which can be used to access it
     */
    url?: null | string;
    /**
     * Optional code language for syntax highlighting
     */
    codeLanguage?: null | string;
    /**
     * Content of the paste. Can be plain text or a valid URL for URL shortening.
     *
     * > [!note]
     * The length of the paste is counted by the number of [UTF-16 code units](https://en.wikipedia.org/wiki/UTF-16#Description)
     */
    content?: null | string;
};

export type UserRole = 'guest' | 'authorized' | 'admin' | 'banned';

export type GetLimitsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/pub/user/limits';
};

export type GetLimitsErrors = {
    /**
     * Too Many Requests
     */
    429: RateLimitError;
};

export type GetLimitsError = GetLimitsErrors[keyof GetLimitsErrors];

export type GetLimitsResponses = {
    /**
     * OK
     */
    200: LimitsResponse;
};

export type GetLimitsResponse = GetLimitsResponses[keyof GetLimitsResponses];

export type GetPastesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of pastes to skip
         */
        offset?: number;
        /**
         * Maximum number of pastes to return
         */
        limit?: number;
    };
    url: '/pub/user/records';
};

export type GetPastesErrors = {
    /**
     * Too Many Requests
     */
    429: RateLimitError;
};

export type GetPastesError = GetPastesErrors[keyof GetPastesErrors];

export type GetPastesResponses = {
    /**
     * OK
     */
    200: PastesListResponse;
};

export type GetPastesResponse = GetPastesResponses[keyof GetPastesResponses];

export type GetProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/pub/user/profile';
};

export type GetProfileErrors = {
    /**
     * Too Many Requests
     */
    429: RateLimitError;
};

export type GetProfileError = GetProfileErrors[keyof GetProfileErrors];

export type GetProfileResponses = {
    /**
     * OK
     */
    200: GetProfileResponse;
};

export type GetProfileResponse2 = GetProfileResponses[keyof GetProfileResponses];

export type CreatePasteData = {
    body: CreatePasteRequest;
    path?: never;
    query?: never;
    url: '/pub/records';
};

export type CreatePasteErrors = {
    /**
     * Bad request
     */
    400: ProblemDetailsResponse;
    /**
     * Too Many Requests
     */
    429: RateLimitError;
    /**
     * Too Many Requests - daily paste limit exceeded
     */
    '429 (daily limit)': ProblemDetailsResponse;
};

export type CreatePasteError = CreatePasteErrors[keyof CreatePasteErrors];

export type CreatePasteResponses = {
    /**
     * OK
     */
    200: CreatePasteResponse;
};

export type CreatePasteResponse2 = CreatePasteResponses[keyof CreatePasteResponses];

export type DeletePasteData = {
    body?: never;
    path: {
        url: string;
    };
    query?: never;
    url: '/pub/records/{url}';
};

export type DeletePasteErrors = {
    /**
     * Too Many Requests
     */
    429: RateLimitError;
};

export type DeletePasteError = DeletePasteErrors[keyof DeletePasteErrors];

export type DeletePasteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetPasteData = {
    body?: never;
    path: {
        url: string;
    };
    query?: never;
    url: '/pub/records/{url}';
};

export type GetPasteErrors = {
    /**
     * Forbidden - access denied
     */
    403: ProblemDetailsResponse;
    /**
     * Bad request - paste not found
     */
    404: ProblemDetailsResponse;
    /**
     * Too Many Requests
     */
    429: RateLimitError;
};

export type GetPasteError = GetPasteErrors[keyof GetPasteErrors];

export type GetPasteResponses = {
    /**
     * OK
     */
    200: GetPasteModel;
};

export type GetPasteResponse = GetPasteResponses[keyof GetPasteResponses];

export type UpdatePasteData = {
    body: UpdatePasteRequest;
    path: {
        url: string;
    };
    query?: never;
    url: '/pub/records/{url}';
};

export type UpdatePasteErrors = {
    /**
     * Too Many Requests
     */
    429: RateLimitError;
};

export type UpdatePasteError = UpdatePasteErrors[keyof UpdatePasteErrors];

export type UpdatePasteResponses = {
    /**
     * OK
     */
    200: CreatePasteResponse;
};

export type UpdatePasteResponse = UpdatePasteResponses[keyof UpdatePasteResponses];
