// This file is auto-generated by @hey-api/openapi-ts

import * as v from 'valibot';

export const vContentType = v.picklist(['text', 'url']);

export const vCreatePasteRequest = v.object({
    url: v.nullish(v.pipe(v.string(), v.minLength(5), v.maxLength(32), v.regex(/^[a-zA-Z|\d]+$/))),
    expirationTime: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647'))),
    codeLanguage: v.nullish(v.pipe(v.string(), v.minLength(0), v.maxLength(30), v.regex(/^[a-zA-Z\d#+-]+$/))),
    content: v.pipe(v.string(), v.minLength(0), v.maxLength(524288))
});

/**
 * Detailed error information for a specific field or validation issue
 */
export const vDetailedErrorItem = v.object({
    field: v.optional(v.string()),
    message: v.string()
});

export const vPastesLimit = v.object({
    limit: v.optional(v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647'))),
    used: v.optional(v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647'))),
    resetsAt: v.optional(v.pipe(v.string(), v.isoTimestamp()))
});

export const vLimitsResponse = v.object({
    pastesLimit: vPastesLimit
});

export const vPasteUserPermission = v.picklist(['edit', 'delete']);

/**
 * Problem details response
 */
export const vProblemDetailsResponse = v.object({
    status: v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    title: v.string(),
    errors: v.optional(v.array(vDetailedErrorItem))
});

/**
 * Rate limit exceeded error response following Problem Details format
 * > [!tip]
 * > All endpoints may return this response
 *
 */
export const vRateLimitError = v.object({
    status: v.literal('429'),
    title: v.literal('You have exceeded the rate limit. Please try again later.'),
    retryAfter: v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647'))
});

export const vSessionType = v.picklist(['web', 'publicApi']);

export const vTextContentType = v.picklist([
    'plainText',
    'code',
    'markdown'
]);

export const vCreatePasteResponse = v.object({
    url: v.string(),
    contentType: vContentType,
    textContentType: v.nullish(vTextContentType)
});

export const vGetPasteModel = v.object({
    url: v.string(),
    content: v.string(),
    contentType: vContentType,
    createdAt: v.pipe(v.string(), v.isoTimestamp()),
    textContentType: v.nullish(vTextContentType),
    codeLanguage: v.nullish(v.string()),
    permissions: v.array(vPasteUserPermission)
});

export const vPastesListResponse = v.object({
    pastes: v.array(vGetPasteModel),
    hasMore: v.boolean()
});

export const vUpdatePasteRequest = v.object({
    url: v.nullish(v.pipe(v.string(), v.minLength(5), v.maxLength(32), v.regex(/^[a-zA-Z|\d]+$/))),
    codeLanguage: v.nullish(v.pipe(v.string(), v.minLength(0), v.maxLength(100))),
    content: v.nullish(v.pipe(v.string(), v.minLength(0), v.maxLength(524288)))
});

export const vUserRole = v.picklist([
    'guest',
    'authorized',
    'admin',
    'banned'
]);

/**
 * The profile of the current user
 */
export const vGetProfileResponse = v.object({
    displayName: v.nullish(v.string()),
    sessionType: vSessionType,
    role: vUserRole
});

export const vGetLimitsData = v.object({
    body: v.optional(v.never()),
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

/**
 * OK
 */
export const vGetLimitsResponse = vLimitsResponse;

export const vGetPastesData = v.object({
    body: v.optional(v.never()),
    path: v.optional(v.never()),
    query: v.optional(v.object({
        offset: v.optional(v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(65535))),
        limit: v.optional(v.pipe(v.number(), v.integer(), v.minValue(1), v.maxValue(40)))
    }))
});

/**
 * OK
 */
export const vGetPastesResponse = vPastesListResponse;

export const vGetProfileData = v.object({
    body: v.optional(v.never()),
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

/**
 * OK
 */
export const vGetProfileResponse2 = vGetProfileResponse;

export const vCreatePasteData = v.object({
    body: vCreatePasteRequest,
    path: v.optional(v.never()),
    query: v.optional(v.never())
});

/**
 * OK
 */
export const vCreatePasteResponse2 = vCreatePasteResponse;

export const vDeletePasteData = v.object({
    body: v.optional(v.never()),
    path: v.object({
        url: v.pipe(v.string(), v.maxLength(100))
    }),
    query: v.optional(v.never())
});

export const vGetPasteData = v.object({
    body: v.optional(v.never()),
    path: v.object({
        url: v.string()
    }),
    query: v.optional(v.never())
});

/**
 * OK
 */
export const vGetPasteResponse = vGetPasteModel;

export const vUpdatePasteData = v.object({
    body: vUpdatePasteRequest,
    path: v.object({
        url: v.pipe(v.string(), v.maxLength(100))
    }),
    query: v.optional(v.never())
});

/**
 * OK
 */
export const vUpdatePasteResponse = vCreatePasteResponse;
